service: clearmail-graphql

custom:
  stage: prod
  debug: "*"
  deploymentBucket: 'global-deployment-bucket'

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.stage}
  region: us-east-1
  deploymentBucket:
    name: ${self:custom.deploymentBucket}
  environment:
    PGHOST: ${ssm:/clearmail/PGHOST}
    PGUSER: postgres
    PGDATABASE: clearmail
    PGPASSWORD: ${ssm:/clearmail/PGPASSWORD~true}
    PGPORT: 5432
    AWS_ACCOUNT_ID: ${ssm:/ACCOUNT_ID}

  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "s3:*"
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "ses:*"
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

functions:
  handler:
    handler: src/handler.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

resources:
  Resources:
    HandlerLogGroup:
      Properties:
        RetentionInDays: 7