language: node_js
node_js:
- 10
branches:
  only:
  - master
install:
  - yarn --ignore-engines
before_script:
  - node_modules/.bin/up-env load --cwd up --aws-region us-east-1
  - yarn --cwd server --ignore-engines
  - yarn --cwd app --ignore-engines
script: 
  - yarn add travis-up
  - up-env load
before_deploy:
  - ls -lat
  - ./bin/up version
deploy:
  provider: script
  script: ./bin/up deploy staging
  skip_cleanup: true

env:
  global:
    AWS_REGION: us-east-1